<<<<<<< HEAD
# Generated by Django 3.0.4 on 2020-05-05 22:25
=======
# Generated by Django 3.0.4 on 2020-05-05 22:31
>>>>>>> 4f7614cde9fcd860c7a4e9c82a4b9a7a95690de0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200505_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
